# Generated by Django 5.2 on 2025-06-08 07:58
# 001_initial.py
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='cakes/')),
                ('cake_type', models.CharField(choices=[('WHIPPING', 'Whipping'), ('SPONGE', 'Sponge'), ('GENOISE', 'Genoise'), ('CHIFFON', 'Chiffon'), ('TIRAMISU', 'Tiramisu')], max_length=50)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
