# Generated by Django 5.2.3 on 2025-06-15 04:22
#0002_alter_cake_cake_type_alter_cake_color_and_more.py
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='cake_type',
            field=models.CharField(choices=[('WHIPPING', 'Whipping'), ('SPONGE', 'Sponge'), ('GENOISE', 'Genoise'), ('CHIFFON', 'Chiffon'), ('TIRAMISU', 'Tiramisu')], max_length=50, verbose_name='Loại bánh'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Màu sắc'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='description',
            field=models.TextField(verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='image',
            field=models.ImageField(upload_to='cakes/', verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tên bánh'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá'),
        ),
    ]
